[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"
authors = ["Ammar Farhan Mohamad Rizam <ammarfmr11@gmail.com>"]
license = "MIT"
license-file = "LICENSE.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
